export default {
  BAD_REQUEST: "BAD_REQUEST",

  CHAT_ID_REQUIRED: "CHAT_ID_REQUIRED",

  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_DATA: "INVALID_DATA",

  NOT_FOUND: "NOT_FOUND",

  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",

  UNAUTHORIZED: "UNAUTHORIZED",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;
