export default {
  CREATED: "CREATED",

  DELETED: "DELETED",

  NOTE_ADDED: "NOTE_ADDED",
  NOTIFICATION_SCHEDULED: "NOTIFICATION_SCHEDULED",

  OK: "OK",

  SCHEDULE_FETCHED: "SCHEDULE_FETCHED",
  SETTINGS_UPDATED: "SETTINGS_UPDATED",

  UPDATED: "UPDATED",
} as const;
