export default {
  CREATED: "CREATED",

  DELETED: "DELETED",

  NOTE_ADDED: "NOTE_ADDED",
  NOTIFICATION_SCHEDULED: "NOTIFICATION_SCHEDULED",

  OK: "OK",

  SCHEDULE_FETCHED: "SCHEDULE_FETCHED",

  UPDATED: "UPDATED",
  USER_DELETED: "USER_DELETED",
  USER_UPDATED: "USER_UPDATED",
  USER_SETTINGS_UPDATED: "USER_SETTINGS_UPDATED",
} as const;
